Work in progress - refactoring
SolarysDev/Volvox.Helios pull request #1
Opened 2018-08-06 09:32 UTC by RethoughtSolutions

More of a concept right now, but major improvements have been already taken from a maintainability and readability point of view. Functionality is a bit unclear right now. Nothing one can't fix though.

The main improvement is code reduction by splitting up responsibility. Which results in less duplicate code. Also more usage of the composition root (Startup.cs), less documentation required.

2018-08-06 21:34 UTC, SolarysDev requested changes

2018-08-06 21:34 UTC, SolarysDev commented on src/Volvox.Helios.Core/Modules/Common/StringTrigger.cs
> +        return false;        }
indent the return statement, push the closing bracket down a line

2018-08-19 18:46 UTC, SolarysDev approved these changes

2018-08-19 18:47 UTC, merged

2018-08-19 19:46 UTC, RethoughtSolutions commented
I spoke with Bill and have more changes on my fork. Some of the stuff was useless and I deleted it.
More soon. /s